# -*- coding: utf-8; mode: python; -*-
#
# Copyright (c) 2013 Sladeware LLC

from blink import sensor, blinker, buttons

propeller_binary(name = "8x8_led_matrix",
                 srcs = ["8x8_led_matrix.c"])

propeller_binary(target = "blink",
                 srcs = [sensor])
